== Component Management and Sonatype Nexus

Presentations and labs labs suitable for a lunch-and-learn/brown bag
session or a user group meeting with sample material available for
anybody interested to use it. 

Please contact marketing@sonatype.com for assistance, if required.

nexus-introduction:: prepared  by Manfred Moser and presented at the
Vancouver Island Java User Group December 2012

nexus-for-component-managerment:: prepared by Manfred Moser and
presented at a Nexus user group meeting in Chicago September 2014

nexus-oss-advantages:: prepared  by Manfred Moser and presented at
JavaOne 2014

=== Tips for Viewing

The html files in the root folder are all you need to show the
presentations. They are self-contained and ready to be used on any
browser.

Find some lab material in the labs folder.

Just download the repo with git clone or as zip/tar.gz

Documentation for writing or using the presentations can be found at 
https://code.google.com/p/asciidoc-slidy2-backend-plugin/.

http://asciidoc-slidy2-backend-plugin.googlecode.com/svn/trunk/doc/slidy2_doc.txt

=== Modifications

If you need to modify and rebuild the slides, modify the source in the
+presentation+ folder and run

----
cd presentation
./generate.sh 
----

asciidoc with slidy2 backend install required.
