== Sonatype Nexus, Sonatype Nexus Lifecycle, Repository Management and the Software Supply Chain

Presentations and labs  suitable for a lunch-and-learn/brown bag
session or a user group meeting with sample material available for
anybody interested to use it. 

Please contact marketing@sonatype.com for assistance, if required.

Now go check out the HTML slide decks at http://sonatype.github.io/nexus-presentations

=== Tips for Viewing

The html files in the root folder are all you need to show the
presentations. They are self-contained and ready to be used on any
browser.

The PDF files are just for being able to print, if desired. 

Find some example material in the +labs+ folder.

Documentation for writing or using the presentations can be found at 
https://code.google.com/p/asciidoc-slidy2-backend-plugin/.

http://asciidoc-slidy2-backend-plugin.googlecode.com/svn/trunk/doc/slidy2_doc.txt

=== Modifications

If you need to modify and rebuild the slides, modify the source in the
+src+ folder and run

----
./generate.sh 
----

asciidoc with slidy2 backend install required.
